<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-1UO0552" ignored="0" name="LoginTest" tests="5" failures="1" timestamp="06 Jul 2021 07:36:46 GMT" time="51.38" errors="0">
  <testcase name="runScenario" time="23.087" classname="cucumber.api.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="23.117" classname="cucumber.api.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="23.179" classname="cucumber.api.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="14.785" classname="cucumber.api.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="12.47" classname="cucumber.api.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.AssertionError" message="Verify user successfully logged out. expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: Verify user successfully logged out. expected [false] but found [true]
at com.duke.pages.AccountOverviewPage.VerifyLogOutSucessfull(AccountOverviewPage.java:44)
at com.duke.stepDefinations.AccountOverviewSteps.verify_user_is_able_to_logout_sucessfully(AccountOverviewSteps.java:40)
at âœ½.Verify user is able to logout sucessfully.(src\test\resources\features\VerifyAccountOverview.feature:22)
... Removed 3 stack frames]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- LoginTest -->
